"""Coherence projection: adjust a set of forecasts to the nearest coherent set.

The coherent forecasts for a check are those generated by some probability
distribution theta over its worlds (see `arbitrage.WORLD_TABLES`):

    q_i(theta) = P(member i resolves yes | member i resolves)

`project` finds the coherent q closest to the given forecasts p, under one of
four notions of "closest":

  klf   minimize sum_i KL(Bern(p_i) || Bern(q_i))
  klr   minimize sum_i KL(Bern(q_i) || Bern(p_i))
  l2    minimize sum_i (p_i - q_i)^2
  game  the coherent set the arbitrage bettor plays against you: maximize the
        guaranteed log-score edge min_w sum_i [ln q_i(w) - ln p_i(w)]

`shrink` moves forecasts part of the way toward the projection.
"""
from __future__ import annotations

import math

import numpy as np
from scipy import optimize

EPS = 1e-4
METHODS = ("klf", "klr", "l2", "game")


def _clip(p: float) -> float:
    return float(min(max(p, EPS), 1 - EPS))


def _q_of_theta(theta, rows) -> np.ndarray:
    qs = []
    for res in rows:
        num = sum(t for t, r in zip(theta, res) if r == 1)
        den = sum(t for t, r in zip(theta, res) if r is not None)
        qs.append(num / max(den, 1e-12))
    return np.array([_clip(q) for q in qs])


def _bern_ll(p: float, outcome: int) -> float:
    return math.log(p if outcome == 1 else 1 - p)


def _theta_of(z: np.ndarray) -> np.ndarray:
    e = np.exp(z - z.max())
    return e / e.sum()


def _inits(ps, rows, k):
    """Starting points: uniform, the forecasts' own implied weights, a perturbation."""
    logw = np.zeros(k)
    for p, res in zip(ps, rows):
        for w in range(k):
            if res[w] is not None:
                logw[w] += _bern_ll(_clip(p), res[w])
    z1 = logw - logw.max()
    rng = np.random.default_rng(0)
    return [np.zeros(k), z1, z1 + rng.normal(0, 0.5, k)]


def project(forecasts: dict[str, float], worlds: dict[str, list[int | None]],
            method: str = "klf") -> dict[str, float]:
    """Nearest coherent forecasts to `forecasts` for the check `worlds`."""
    if method not in METHODS:
        raise ValueError(f"method must be one of {METHODS}")
    members = list(worlds)
    rows = [worlds[m] for m in members]
    ps = np.array([_clip(forecasts[m]) for m in members])
    k = len(rows[0])

    if method != "game":
        def obj(z):
            q = _q_of_theta(_theta_of(z), rows)
            if method == "klf":
                return float(np.sum(ps * np.log(ps / q) + (1 - ps) * np.log((1 - ps) / (1 - q))))
            if method == "klr":
                return float(np.sum(q * np.log(q / ps) + (1 - q) * np.log((1 - q) / (1 - ps))))
            return float(np.sum((ps - q) ** 2))

        best = min((optimize.minimize(obj, z0, method="L-BFGS-B") for z0 in _inits(ps, rows, k)),
                   key=lambda r: r.fun)
    else:
        def neg_soft_min_edge(z, temp=60.0):
            q = _q_of_theta(_theta_of(z), rows)
            edges = np.array([
                sum(_bern_ll(qi, res[w]) - _bern_ll(pi, res[w])
                    for qi, pi, res in zip(q, ps, rows) if res[w] is not None)
                for w in range(k)])
            return float(np.log(np.sum(np.exp(-temp * edges))) / temp)

        best = min((optimize.minimize(neg_soft_min_edge, z0, method="Nelder-Mead",
                                      options={"maxiter": 800, "xatol": 1e-5, "fatol": 1e-8})
                    for z0 in _inits(ps, rows, k)), key=lambda r: r.fun)
    q = _q_of_theta(_theta_of(best.x), rows)
    return {m: float(v) for m, v in zip(members, q)}


def shrink(forecasts: dict[str, float], coherent: dict[str, float], weight: float,
           space: str = "probability") -> dict[str, float]:
    """Move each forecast `weight` of the way (0 to 1) toward its coherent value,
    in probability space or log-odds space."""
    out = {}
    for m, p in forecasts.items():
        p, q = _clip(p), _clip(coherent[m])
        if space == "probability":
            out[m] = (1 - weight) * p + weight * q
        elif space == "log_odds":
            lo = (1 - weight) * math.log(p / (1 - p)) + weight * math.log(q / (1 - q))
            out[m] = 1 / (1 + math.exp(-lo))
        else:
            raise ValueError("space must be 'probability' or 'log_odds'")
    return out
