"""Squiggle Hub (squigglehub.org) adapter.

Models are Squiggle *code*, so unlike Guesstimate the graph is implicit: we
lex the source, find variable bindings (nodes) — including bindings nested in
dict blocks, where most models keep their real structure — and link an edge
whenever a binding's RHS references another binding (input -> dependent).

Endpoints (public, no auth; found in quantified-uncertainty/squiggle
apps/hub/src/app/api):
  /api/find-owners?search=<s>&mode=all-users|all-groups   (contains-match, take 20)
  /api/get-group-models?slug=<owner>                      (works for users too, limit 100)
  /api/get-source?owner=<o>&slug=<s>

AI provenance: the hub's own "publish from AI workflow" flow prepends
  /* Generated by Squiggle AI. Workflow ID: ... */
(PublishWorkflowButton.tsx) — a definitive marker. Manual copy-paste from
Squiggle AI loses it, so we also compute style fingerprints matching the
Squiggle AI generation prompt's mandated style: @name/@doc annotations (often
with emoji), sTest imports and *_tests describe blocks.

The lexer is heuristic (no real Squiggle parser in Python): comments/strings
blanked, bracket-depth tracked, expression ends found by newline-at-base-depth
with operator-continuation checks. Good enough for dependency structure; not a
compiler.
"""
from __future__ import annotations

import json
import re
import urllib.parse
import urllib.request
from pathlib import Path

from .ir import Edge, MapIR, slugify

BASE = "https://squigglehub.org/api"

AI_HEADER = re.compile(r"Generated by Squiggle AI\.?\s*Workflow ID:\s*([\w-]+)")

KEYWORDS = {
    "if", "then", "else", "to", "import", "as", "true", "false", "and", "or",
    "not", "in", "with", "export",
}
# stdlib namespaces — never link refs to these
BUILTINS = {
    "SampleSet", "Dist", "List", "String", "Math", "Tag", "Plot", "Table",
    "Calculator", "Danger", "Date", "Duration", "Sym", "Spec", "MixedSet",
    "Number", "Boolean", "Dict", "Input", "PointSet", "Scale", "System",
}

BINDING_RE = re.compile(r"(?<![\w.])([A-Za-z_]\w*)\s*(\([^()]*\))?\s*=(?![=>])")
ANNOTATION = re.compile(r"@(name|doc)\(\s*\"((?:[^\"\\]|\\.)*)\"", re.S)
IMPORT = re.compile(r"import\s+\"hub:([\w./-]+)/([\w.-]+)\"\s+as\s+([A-Za-z_]\w*)")
DOTTED = re.compile(r"[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*")
# a line ENDING with one of these means the expression continues below;
# a line STARTING with one of these continues the previous expression.
# brackets are deliberately excluded: an unclosed bracket is already handled by
# the depth check, and a fresh line starting with "{" is a dict return value.
CONTINUATION_END = set("+-*/.|&<>=:,?(")
CONTINUATION_START = set("+-*/.|&<>=:,?")


def api_get(path: str, retries: int = 3, **params) -> dict | list:
    import time
    url = f"{BASE}/{path}?{urllib.parse.urlencode(params)}"
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read())
        except Exception:
            if attempt == retries - 1:
                raise
            time.sleep(5 * (attempt + 1))


def fetch_model_source(owner: str, slug: str) -> str:
    return api_get("get-source", owner=owner, slug=slug)["code"]


# ---------- lexing ----------

def strip_comments_strings(code: str) -> str:
    """Blank out comments and string literals, preserving offsets/newlines."""
    out = list(code)
    i, n = 0, len(code)
    while i < n:
        c = code[i]
        if c == "/" and i + 1 < n and code[i + 1] == "/":
            j = code.find("\n", i)
            j = n if j == -1 else j
            for k in range(i, j):
                out[k] = " "
            i = j
        elif c == "/" and i + 1 < n and code[i + 1] == "*":
            j = code.find("*/", i + 2)
            j = n if j == -1 else j + 2
            for k in range(i, j):
                if out[k] != "\n":
                    out[k] = " "
            i = j
        elif c in "\"'":
            q = c
            j = i + 1
            while j < n and code[j] != q:
                j += 2 if code[j] == "\\" else 1
            j = min(j + 1, n)
            for k in range(i, j):
                if out[k] != "\n":
                    out[k] = " "
            i = j
        else:
            i += 1
    clean = "".join(out)
    # decorators and lambda param lists would tokenize as identifiers — blank them
    clean = re.sub(r"@[A-Za-z_]\w*", lambda m: " " * len(m.group()), clean)
    clean = re.sub(r"\{\s*\|[^|]*\|",
                   lambda m: "{" + " " * (len(m.group()) - 1), clean)
    return clean


def _depths(clean: str) -> list[int]:
    """Bracket depth *before* each character."""
    depth = [0] * len(clean)
    d = 0
    for i, c in enumerate(clean):
        depth[i] = d
        if c in "([{":
            d += 1
        elif c in ")]}":
            d = max(0, d - 1)
    return depth


def _match_brace(clean: str, i: int) -> int | None:
    d = 0
    for j in range(i, len(clean)):
        if clean[j] in "([{":
            d += 1
        elif clean[j] in ")]}":
            d -= 1
            if d == 0:
                return j
    return None


def _expr_end(clean: str, depth: list[int], start: int, limit: int,
              base_depth: int) -> int:
    """Where the expression starting at `start` ends: the first newline at base
    depth where neither the previous line ends with a continuation operator nor
    the next line starts with one."""
    i = start
    while i < limit:
        if clean[i] == "\n" and (i + 1 >= limit or depth[i + 1] <= base_depth):
            k = i - 1
            while k >= start and clean[k] in " \t\n":
                k -= 1
            if k < start:  # empty so far, keep scanning
                i += 1
                continue
            if clean[k] in CONTINUATION_END:
                i += 1
                continue
            j = i + 1
            while j < limit and clean[j] in " \t\n":
                j += 1
            if j >= limit:
                return limit
            if clean[j] in CONTINUATION_START or clean[j:j + 2] == "->":
                i += 1
                continue
            return i
        i += 1
    return limit


def _parse_scope(code: str, clean: str, depth: list[int], start: int, end: int,
                 base_depth: int, path: tuple, out: list):
    """Collect bindings in [start, end) at exactly base_depth, recursing into
    dict-block RHSes. Appends dicts to `out`."""
    matches = [m for m in BINDING_RE.finditer(clean, start, end)
               if depth[m.start(1)] == base_depth and m.group(1) not in KEYWORDS]
    prev_end = start
    for m in matches:
        if m.start() < prev_end:  # inside a previous binding's expression
            continue
        rhs_start = m.end()
        expr_end = _expr_end(clean, depth, rhs_start, end, base_depth)
        gap = code[prev_end:m.start()]
        anns = {a.group(1): a.group(2).strip() for a in ANNOTATION.finditer(gap)}
        rec = {
            "name": m.group(1), "params": m.group(2) or "", "path": path,
            "qual": path + (m.group(1),),
            "start": m.start(), "rhs_start": rhs_start, "end": expr_end,
            "annotations": anns, "children": [],
        }
        out.append(rec)
        # dict-block RHS? recurse
        j = rhs_start
        while j < expr_end and clean[j] in " \t\n":
            j += 1
        if j < expr_end and clean[j] == "{":
            close = _match_brace(clean, j)
            if close is not None and close < expr_end:
                n_before = len(out)
                _parse_scope(code, clean, depth, j + 1, close,
                             base_depth + 1, rec["qual"], out)
                rec["children"] = [r["qual"] for r in out[n_before:]
                                   if len(r["qual"]) == len(rec["qual"]) + 1]
        prev_end = expr_end
    return out


def parse_squiggle(code: str) -> dict:
    clean = strip_comments_strings(code)
    depth = _depths(clean)
    bindings: list[dict] = []
    _parse_scope(code, clean, depth, 0, len(clean), 0, (), bindings)

    imports = [{"owner": m.group(1), "slug": m.group(2), "alias": m.group(3)}
               for m in IMPORT.finditer(code)]

    # ref region per binding = its RHS minus descendant binding spans
    by_qual = {b["qual"]: b for b in bindings}
    for b in bindings:
        descendants = [d for d in bindings
                       if d["qual"][:len(b["qual"])] == b["qual"] and d is not b]
        cuts = sorted((d["start"], d["end"]) for d in descendants)
        region, pos = [], b["rhs_start"]
        for cs, ce in cuts:
            if cs > pos:
                region.append(clean[pos:cs])
            pos = max(pos, ce)
        if b["end"] > pos:
            region.append(clean[pos:b["end"]])
        text = " ".join(region)
        params = set(re.findall(r"[A-Za-z_]\w*", b["params"]))
        b["refs"] = [t for t in dict.fromkeys(DOTTED.findall(text))
                     if t.split(".")[0] not in params
                     and t.split(".")[0] not in KEYWORDS
                     and t.split(".")[0] not in BUILTINS
                     and t != b["name"]]
    return {"bindings": bindings, "imports": imports, "by_qual": by_qual}


# ---------- AI fingerprints ----------

def ai_signals(code: str, n_bindings: int | None = None) -> dict:
    header = AI_HEADER.search(code)
    if n_bindings is None:
        n_bindings = len(parse_squiggle(code)["bindings"])
    n_name = len(re.findall(r"@name\(", code))
    emoji_names = len(re.findall(r"@name\(\"[^\"]*[\U0001F300-\U0001FAFF☀-➿]", code))
    return {
        "ai_workflow_id": header.group(1) if header else None,
        "sTest": bool(re.search(r"hub:ozziegooen/sTest", code)),
        "tests_vars": len(re.findall(r"\w*[Tt]ests?\s*=\s*sTest\.describe", code)),
        "name_annotation_density": round(n_name / max(1, n_bindings), 3),
        "emoji_name_annotations": emoji_names,
        "doc_annotations": len(re.findall(r"@doc\(", code)),
    }


AI_SLUG_HINT = re.compile(r"ai[-_]?(generated|bottle|example|model|test)|squiggle[-_]?ai",
                          re.I)


def ai_verdict(sig: dict, owner: str = "", slug: str = "") -> str:
    """'confirmed' (hub AI header), 'likely' (style fingerprints or an
    AI-flavored owner/slug), 'unknown'."""
    if sig["ai_workflow_id"]:
        return "confirmed"
    score = ((sig["sTest"] and sig["tests_vars"] > 0)
             + (sig["name_annotation_density"] >= 0.4)
             + (sig["emoji_name_annotations"] >= 2))
    if AI_SLUG_HINT.search(f"{owner}/{slug}"):
        score += 1
    return "likely" if score >= 2 else "unknown"


# ---------- IR ----------

def _resolve(token: str, scope: tuple, by_qual: dict, aliases: dict) -> tuple | str | None:
    """Resolve a (possibly dotted) reference from a binding at `scope` (its
    path). Returns a qual tuple, an alias name, or None."""
    parts = token.split(".")
    for k in range(len(scope), -1, -1):  # innermost scope outward
        base = scope[:k] + (parts[0],)
        if base in by_qual:
            qual = base
            for p in parts[1:]:
                if qual + (p,) in by_qual:
                    qual = qual + (p,)
                else:
                    break
            return qual
    if parts[0] in aliases:
        return parts[0]
    return None


def from_squiggle_code(code: str, name: str, meta: dict | None = None) -> MapIR:
    parsed = parse_squiggle(code)
    bindings, by_qual = parsed["bindings"], parsed["by_qual"]
    taken: set[str] = set()
    qual_to_slug: dict[tuple, str] = {}
    nodes: dict[str, dict] = {}
    for b in bindings:
        title = b["annotations"].get("name") or b["name"]
        slug = slugify(title, taken)
        qual_to_slug[b["qual"]] = slug
        if b["params"]:
            ntype = "squiggle_function"
        elif b["children"]:
            ntype = "squiggle_dict"
        else:
            ntype = "squiggle_binding"
        nodes[slug] = {
            "title": title,
            "desc": b["annotations"].get("doc", ""),
            "is_main": False,
            "node_type": ntype,
            "squiggle": {"variable": ".".join(b["qual"])},
        }
    aliases = {imp["alias"]: imp for imp in parsed["imports"]}
    alias_to_slug: dict[str, str] = {}

    def import_node(alias: str) -> str:
        if alias not in alias_to_slug:
            imp = aliases[alias]
            slug = slugify(f"import {imp['owner']}/{imp['slug']}", taken)
            alias_to_slug[alias] = slug
            nodes[slug] = {"title": f"{imp['owner']}/{imp['slug']}", "desc": "",
                           "is_main": False, "node_type": "import",
                           "squiggle": {"variable": alias}}
        return alias_to_slug[alias]

    edges: list[Edge] = []
    seen: set[tuple[str, str]] = set()
    for b in bindings:
        target = qual_to_slug[b["qual"]]
        for token in b["refs"]:
            # scope = own qual: a container's return expression lives inside
            # its block, so its own children are in scope
            res = _resolve(token, b["qual"], by_qual, aliases)
            if res is None:
                continue
            source = import_node(res) if isinstance(res, str) else qual_to_slug[res]
            if source == target or (source, target) in seen:
                continue
            # a container referencing its own child is the child feeding the
            # container's return value: keep child -> container only
            seen.add((source, target))
            edges.append(Edge(source=source, target=target, type="causal",
                              directed=True,
                              provenance={"from": "squiggle_reference"}))
    sig = ai_signals(code, n_bindings=len(bindings))
    verdict = ai_verdict(sig, owner=(meta or {}).get("owner", ""),
                         slug=(meta or {}).get("slug", ""))
    ir = MapIR(name=name, nodes=nodes, edges=edges,
               meta={"source": "squigglehub",
                     "imports": parsed["imports"],
                     "ai_signals": sig, "ai_verdict": verdict,
                     **(meta or {})})
    slug_to_qual = {v: k for k, v in qual_to_slug.items()}
    for slug in ir.sinks():
        var = ir.nodes[slug]["squiggle"]["variable"]
        if re.search(r"[Tt]ests?$", var):
            continue
        # an input-collection dict whose only in-edges are its own children is
        # not an output, even though it's a sink
        qual = slug_to_qual.get(slug)
        if qual is not None and ir.nodes[slug]["node_type"] == "squiggle_dict":
            incoming = [e.source for e in ir.edges if e.target == slug]
            children = {qual_to_slug[q] for q in by_qual[qual].get("children", [])
                        if q in qual_to_slug}
            if incoming and all(s in children for s in incoming):
                continue
        ir.nodes[slug]["is_main"] = True
    return ir
